pipeline:
  identifier: Build_Harness_test1_1725572633014
  name: Build Harness_test1
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.vrquad
        repoName: Harness_test1
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: sh 'noxfile.py'
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Python
                    buildTool: Pytest
                    runOnlySelectedTests: true
                    enableTestSplitting: false
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
